#!/usr/bin/env sh

BOILER_PLATE_DIR="$HOME/Documents/github/boilerplate/templates"

# NOTE: improve this with multiselection `-m`
select_template() {
	fd --base-directory="$BOILER_PLATE_DIR" \
		--hidden \
		--type=file \
		--exclude="*.md" |
		fzf --multi --preview "cat $BOILER_PLATE_DIR/{}" \
			--preview-window=right:60% \
			--header="Select a template (ESC to exit)"

}

copy_to_clipboard() {
	template_path="$1"
	filename=$(basename "$1")
	xclip -selection clipboard <"$template_path"
	printf "File %s has succsessfully copied to the clipboard" "$filename"
	return 0
}

main() {
	selected_templates=$(select_template)
	[ -z "$selected_templates" ] && exit 1

	for template in $selected_templates; do
		full_template_path="$BOILER_PLATE_DIR/$template"

		if [ ! -f "$full_template_path" ]; then
			echo "Error: Template file not found: $full_template_path"
			exit 1
		fi

		copy_to_clipboard "$full_template_path"
		echo ""
	done
}

main
