#!/usr/bin/env sh

COPY_MESSAGE=""
CREATED_MESSAGE=""
BOILER_PLATE_DIR="$HOME/Documents/github/boilerplate/templates"

select_template() {
  fd --base-directory="$BOILER_PLATE_DIR" \
    --hidden \
    --type=file \
    --exclude="*.md" |
    fzf --preview "bat --color=always --style=numbers $BOILER_PLATE_DIR/{}" \
      --preview-window=right:60% \
      --header="Select a template (ESC to exit)"

}

copy_to_clipboard() {
  printf "Copy file to clipboard? (y/n) " && read -r response

  [ "$response" = "n" ] && return 0

  filename=$(basename "$1")
  if bat "$1" | xclip -selection clipboard; then
    COPY_MESSAGE="✓ $filename has been copied"
    return 0
  fi

  echo "✗ Failed to copy to clipboard"
  return 1
}

create_file_in_dir() {
  filename=$(basename "$1")
  dest="$(pwd)/$filename"

  printf "Create file in current directory? (y/n) " &&
    read -r response

  [ "$response" = "n" ] && return 0

  if [ -f "$dest" ]; then
    printf "File already exist, overwrite it? (y/n) " &&
      read -r overwrite

    [ "$overwrite" != "y" ] && return 0
  fi

  if cp "$1" "$dest"; then
    CREATED_MESSAGE="✓ $filename has been created"
    return 0
  fi

  echo "✗ Failed to create file"
  return 1
}

main() {
  selected_template=$(select_template)

  [ -z "$selected_template" ] && exit 1

  full_template_path="$BOILER_PLATE_DIR/$selected_template"

  if [ ! -f "$full_template_path" ]; then
    echo "Error: Template file not found: $full_template_path"
    exit 1
  fi

  copy_to_clipboard "$full_template_path"
  create_file_in_dir "$full_template_path"

  [ -n "$COPY_MESSAGE" ] && echo "$COPY_MESSAGE"
  [ -n "$CREATED_MESSAGE" ] && echo "$CREATED_MESSAGE"
}

main
